server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.server.webmvc.routes[0].id=wallet-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://wallet-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/wallet/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=3

spring.cloud.gateway.server.webmvc.routes[1].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://inventory-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/inventory/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=3

spring.cloud.gateway.server.webmvc.routes[2].id=shop-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://shop-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/shop/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=3

spring.cloud.gateway.server.webmvc.routes[3].id=wallet-docs-v1
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://wallet-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/docs/v1/wallet
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=RewritePath=/docs/v1/wallet, /v3/api-docs

spring.cloud.gateway.server.webmvc.routes[4].id=inventory-docs-v1
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://inventory-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/docs/v1/inventory
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=RewritePath=/docs/v1/inventory, /v3/api-docs

spring.cloud.gateway.server.webmvc.routes[5].id=shop-docs-v1
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://shop-service
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/docs/v1/shop
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=RewritePath=/docs/v1/shop, /v3/api-docs

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=wallet-service (v1)
springdoc.swagger-ui.urls[0].url=/docs/v1/wallet
springdoc.swagger-ui.urls[1].name=inventory-service (v1)
springdoc.swagger-ui.urls[1].url=/docs/v1/inventory
springdoc.swagger-ui.urls[2].name=shop-service (v1)
springdoc.swagger-ui.urls[2].url=/docs/v1/shop

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true